name: Spicord
author: Sheidy
version: ${project.version}
main: org.spicord.bukkit.SpicordBukkit
description: Discord integration for BungeeCord and Bukkit/Spigot servers.
commands:
  spicord:
    description: The main command of Spicord
    aliases: [sp]
