name: Spicord
author: Tini
version: ${project.version}
main: org.spicord.bukkit.SpicordBukkit
api-version: 1.13
folia-supported: true
description: Discord integration for BungeeCord and Bukkit/Spigot servers.
commands:
  spicord:
    description: The main command of Spicord
    aliases: [sp]
